services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - php
      - mysql
    container_name: docker_nginx

  php:
    build:
      context: ./_docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    container_name: docker_php

  mysql:
    image: mysql:8.0
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    depends_on:
      - phpmyadmin
    container_name: docker_mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    container_name: docker_phpmyadmin

  node:
    image: node:20.15.0-alpine
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
    container_name: docker_node